# Generated by Django 4.1 on 2022-08-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
            ],
            options={
                "db_table": "airports",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "continents",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOfATrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip", models.CharField(max_length=10)),
                ("participant_details", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
            ],
            options={
                "db_table": "purchasesfortrip",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_departure", models.DateField(null=True)),
                ("date_of_return", models.DateField(null=True)),
                ("number_of_days", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (" BB ", "bed & breakfast"),
                            (" HB ", "half board"),
                            (" FB ", "full board"),
                            (" AI ", "all inclusive"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price_for_adult", models.IntegerField()),
                ("price_for_child", models.IntegerField()),
                ("promoted", models.BooleanField(default=False)),
                ("number_of_places_per_adult", models.IntegerField()),
                ("number_of_places_per_child", models.IntegerField()),
                (
                    "Airport_from_where",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airport from where +",
                        to="administrator.airport",
                        verbose_name="airport from where",
                    ),
                ),
                (
                    "airport_to_where",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airport to where +",
                        to="administrator.airport",
                        verbose_name="airport to where",
                    ),
                ),
                (
                    "city_from_where",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city from where +",
                        to="administrator.city",
                        verbose_name="city from where",
                    ),
                ),
                (
                    "city_to_where",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city to where +",
                        to="administrator.city",
                        verbose_name="city to where",
                    ),
                ),
                (
                    "hotel_to_where",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel to where +",
                        to="administrator.city",
                        verbose_name="hotel to where",
                    ),
                ),
            ],
            options={
                "db_table": "trips",
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                ("photo", models.ImageField(null=True, upload_to="hotels")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.city",
                        verbose_name="city",
                    ),
                ),
            ],
            options={
                "db_table": "hotels",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "continent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.continent",
                        verbose_name="continent",
                    ),
                ),
            ],
            options={
                "db_table": "countries",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.country",
                verbose_name="country",
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.city",
                verbose_name="city",
            ),
        ),
    ]
