# Generated by Django 4.1 on 2022-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseofatrip",
            name="price_adult",
        ),
        migrations.RemoveField(
            model_name="purchaseofatrip",
            name="price_child",
        ),
        migrations.AddField(
            model_name="purchaseofatrip",
            name="quantity_a",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="purchaseofatrip",
            name="quantity_ch",
            field=models.IntegerField(default=0),
        ),
    ]
