# Generated by Django 4.1 on 2022-09-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrator",
            "0002_rename_airport_from_where_trip_airport_from_where_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseofatrip",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="purchaseofatrip",
            name="participant_details",
        ),
        migrations.AddField(
            model_name="purchaseofatrip",
            name="number_of_adults_participant",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseofatrip",
            name="number_of_child_participant",
            field=models.IntegerField(default=0),
        ),
    ]
