# Generated by Django 4.1 on 2022-09-21 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0002_remove_purchaseofatrip_price_adult_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseofatrip",
            name="trip",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="administrator.trip",
                verbose_name="trip",
            ),
        ),
    ]
