# Generated by Django 4.1 on 2022-09-18 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0003_remove_purchaseofatrip_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseofatrip",
            name="number_of_adults_participant",
        ),
        migrations.RemoveField(
            model_name="purchaseofatrip",
            name="number_of_child_participant",
        ),
        migrations.AddField(
            model_name="purchaseofatrip",
            name="purchased_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseofatrip",
            name="quantity_a",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="purchaseofatrip",
            name="quantity_ch",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="purchaseofatrip",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="administrator.trip",
                verbose_name="trip",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="number_of_places_per_adult",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="trip",
            name="number_of_places_per_child",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="trip",
            name="price_for_adult",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="trip",
            name="price_for_child",
            field=models.IntegerField(default=15),
        ),
        migrations.AlterModelTable(
            name="purchaseofatrip",
            table="purchases",
        ),
    ]
