# Generated by Django 4.1 on 2022-09-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_remove_trip_number_of_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="date_of_departure",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="date_of_return",
            field=models.DateTimeField(null=True),
        ),
    ]
