# Generated by Django 4.1 on 2022-09-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0005_alter_trip_date_of_departure_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_date", models.DateField()),
                ("second_date", models.DateField()),
            ],
        ),
    ]
