# Generated by Django 4.1 on 2022-09-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0006_filterdate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trip",
            options={
                "permissions": [("addtrip", " Add Trip"), ("deletetrip", "Delete Trip")]
            },
        ),
        migrations.AlterField(
            model_name="filterdate",
            name="first_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="filterdate",
            name="second_date",
            field=models.DateTimeField(),
        ),
    ]
