# Generated by Django 4.1 on 2022-10-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0015_post_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="trip",
        ),
    ]
