# Generated by Django 4.1 on 2022-10-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0016_remove_post_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="trip",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_post",
                to="administrator.trip",
            ),
        ),
    ]
