# Generated by Django 4.1 on 2022-10-24 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("administrator", "0021_post_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="liked",
        ),
        migrations.AddField(
            model_name="trip",
            name="liked",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="liked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
