# Generated by Django 4.1 on 2022-10-30 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0024_rename_author_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.AddField(
            model_name="like",
            name="trip",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.trip",
            ),
        ),
    ]
