# Generated by Django 4.1 on 2022-10-30 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0025_remove_like_post_like_trip"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
