# Generated by Django 4.1 on 2022-11-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0027_like"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
